### ISSUE TITLE
JSON error after token retrieval

### ISSUE THREAD

**Issue by Dhtjf** [dbrand666/usmobile-lifeguard#7]
Updated from the prior version, starting from scratch, after my token expired. Built from cloning the repo and config updated. Running on Windows in Docker Desktop.
When running, it obtains a token after trying a few times but then errors out and goes to sleep (reduced to 1 minute here for testing). Is this an error on my part or something different? Thanks!

`2023-09-01 12:26:53 usmobile-lifeguard  | Failed to get token - retrying...
2023-09-01 12:27:10 usmobile-lifeguard  | Got a new token!
2023-09-01 12:27:10 usmobile-lifeguard  | Unexpected err=JSONDecodeError('Expecting value: line 1 column 1 (char 0)'), type(err)=<class 'requests.exceptions.JSONDecodeError'>
2023-09-01 12:27:10 usmobile-lifeguard  | Sleeping for 1.0 minutes.`

**Comment by dbrand666** [comment]
Yup. I'm seeing the same problem this morning. Looking at it right now.

Edit 1: It looks like they've tightened their Cloudflare config - maybe turned on [Under Attack mode](https://developers.cloudflare.com/fundamentals/reference/under-attack-mode/).

**Comment by Dhtjf** [comment]
Thanks @dbrand666 for your work on this!

I'm now getting
`2023-09-01 23:46:10 usmobile-lifeguard  | Unexpected err=HTTPError('403 Client Error: Forbidden for url: https://api.usmobile.com/web-gateway/api/v1/pools/XXXXX'), type(err)=<class 'requests.exceptions.HTTPError'>`
XXXXX being my pool ID. I verified the pool ID is accurate.

**Comment by dbrand666** [comment]
Yup. The new version ran for a few hours but I see it's getting that error now too. Looks like I'll need to try something else.

**Comment by dbrand666** [comment]
Sorry. I haven't had much time this week to deal with this, but... to my surprise, it looks like USMobile actually implemented auto top up themselves!

I enabled it on my account. Assuming it works as advertised, I'm not planning on doing anything further with this.

**Comment by Dhtjf** [comment]
Thanks for the heads-up and I added it to my account. Thanks for making this before they released their own!

**Comment by gazpachoking** [comment]
Agreed. Thanks for this, and the notice. Also enabled on my account. It says that the top-ups roll over now? That wasn't the case for pooled plans before, hopefully that's accurate.

**Comment by dbrand666** [comment]
The rollovers seem to be working. I discovered it last month by accident - I had to top up just days before plan renewal and was pleasantly surprised to see it roll over.
